#cloud-config
bootcmd:
 - set +x
 - echo 'Acquire::Languages "none";' > tee /etc/apt/apt.conf.d/02nolang
 - sed -i -e 's/^deb-src/#deb-src/' /etc/apt/sources.list
 - rm -f /etc/dpkg/dpkg.cfg.d/multiarch
 - dpkg --remove-architecture i386
 - apt-get purge -y apt-xapian-index python-twisted-core ntfs-3g
apt-sources:
    - cloud-archive:newton
packages:
    - memcached
    - swift
    - swift-account
    - swift-container
    - swift-object
    - swift-proxy
write_files:
    - path: /etc/swift/swift.conf
      content: |
          [swift-hash]
          swift_hash_path_suffix = changem
          swift_hash_path_prefix = changem
    - path: /etc/swift/account-server.conf
      content: |
          [DEFAULT]
          bind_ip = 0.0.0.0
          bind_port = 6002
          user = swift
          swift_dir = /etc/swift
          devices = /srv/node
          mount_check = false
          [pipeline:main]
          pipeline = healthcheck recon account-server
          [app:account-server]
          use = egg:swift#account
          [filter:healthcheck]
          use = egg:swift#healthcheck
          [filter:recon]
          use = egg:swift#recon
          recon_cache_path = /var/cache/swift
    - path: /etc/swift/container-server.conf
      content: |
          [DEFAULT]
          bind_ip = 0.0.0.0
          bind_port = 6001
          user = swift
          swift_dir = /etc/swift
          devices = /srv/node
          mount_check = false
          [pipeline:main]
          pipeline = healthcheck recon container-server
          [app:container-server]
          use = egg:swift#container
          [filter:healthcheck]
          use = egg:swift#healthcheck
          [filter:recon]
          use = egg:swift#recon
          recon_cache_path = /var/cache/swift
    - path: /etc/swift/object-server.conf
      content: |
          [DEFAULT]
          bind_ip = 0.0.0.0
          bind_port = 6000
          user = swift
          swift_dir = /etc/swift
          devices = /srv/node
          mount_check = false
          [pipeline:main]
          pipeline = healthcheck recon object-server
          [app:object-server]
          use = egg:swift#object
          [filter:healthcheck]
          use = egg:swift#healthcheck
          [filter:recon]
          use = egg:swift#recon
          recon_cache_path = /var/cache/swift
          recon_lock_path = /var/lock
    - path: /etc/swift/proxy-server.conf
      content: |
          [DEFAULT]
          bind_ip = 0.0.0.0
          bind_port = 8080
          swift_dir = /etc/swift
          user = swift
          [pipeline:main]
          pipeline = catch_errors gatekeeper healthcheck proxy-logging cache container_sync bulk tempurl ratelimit tempauth container-quotas account-quotas slo dlo versioned_writes proxy-logging proxy-server
          [app:proxy-server]
          use = egg:swift#proxy
          account_autocreate = true
          [filter:tempauth]
          use = egg:swift#tempauth
          user_admin_admin = admin .admin .reseller_admin
          user_test_tester = testing .admin
          user_test2_tester2 = testing2 .admin
          user_test_tester3 = testing3
          user_test5_tester5 = testing5 service
          [filter:healthcheck]
          use = egg:swift#healthcheck
          [filter:cache]
          use = egg:swift#memcache
          [filter:ratelimit]
          use = egg:swift#ratelimit
          [filter:domain_remap]
          use = egg:swift#domain_remap
          [filter:catch_errors]
          use = egg:swift#catch_errors
          [filter:cname_lookup]
          use = egg:swift#cname_lookup
          [filter:staticweb]
          use = egg:swift#staticweb
          [filter:tempurl]
          use = egg:swift#tempurl
          [filter:formpost]
          use = egg:swift#formpost
          [filter:name_check]
          use = egg:swift#name_check
          [filter:list-endpoints]
          use = egg:swift#list_endpoints
          [filter:proxy-logging]
          use = egg:swift#proxy_logging
          [filter:bulk]
          use = egg:swift#bulk
          [filter:slo]
          use = egg:swift#slo
          [filter:dlo]
          use = egg:swift#dlo
          [filter:container-quotas]
          use = egg:swift#container_quotas
          [filter:account-quotas]
          use = egg:swift#account_quotas
          [filter:gatekeeper]
          use = egg:swift#gatekeeper
          [filter:container_sync]
          use = egg:swift#container_sync
          [filter:xprofile]
          use = egg:swift#xprofile
          [filter:versioned_writes]
          use = egg:swift#versioned_writes
runcmd:
    - mkdir -p /srv/node
    - chown swift:swift /srv/node
    - swift-ring-builder account.builder create 9 1 1
    - swift-ring-builder container.builder create 9 1 1
    - swift-ring-builder object.builder create 9 1 1
    - swift-ring-builder account.builder add z1-127.0.0.1:6002/dir 1
    - swift-ring-builder container.builder add z1-127.0.0.1:6001/dir 1
    - swift-ring-builder object.builder add z1-127.0.0.1:6000/dir 1
    - swift-ring-builder account.builder rebalance
    - swift-ring-builder container.builder rebalance
    - swift-ring-builder object.builder rebalance
    - cp *.gz /etc/swift
    - service memcached start
    - service swift-account start
    - service swift-container start
    - service swift-object start
    - service swift-proxy start
ssh_import_id: ["gh:jrwren"] # change this to your lp:id or gh:id
